services:
  # 1. Banco de Dados
  postgres:
    image: postgres:16-alpine
    container_name: paroquia_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - paroquia_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # 2. Backend API
  backend:
    build:
      context: ./backend
    container_name: paroquia_backend
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${DB_PORT}/${POSTGRES_DB}?schema=public
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - paroquia_network

  # 3. Frontend Site (Público)
  frontend-site:
    build:
      context: ./frontend-site
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: paroquia_site
    restart: unless-stopped
    networks:
      - paroquia_network

  # 4. Frontend Admin (Privado)
  frontend-admin:
    build:
      context: ./frontend-admin
      args:
        VITE_API_URL: ${VITE_API_URL}
    container_name: paroquia_admin
    restart: unless-stopped
    networks:
      - paroquia_network

  # 5. Load Balancer (Nginx Reverso)
  proxy:
    build:
      context: ./proxy
    container_name: paroquia_proxy
    restart: unless-stopped
    ports:
      - "80:80"     
      - "8081:8081" 
    depends_on:
      - backend
      - frontend-site
      - frontend-admin
    networks:
      - paroquia_network

  # 6. CI/CD (Jenkins)
  jenkins:
    build:
      context: ./jenkins
    container_name: paroquia_jenkins
    restart: unless-stopped
    ports:
      - "8080:8080" # Porta de acesso ao painel do Jenkins
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      # Mapeia o socket do docker hospedeiro para o jenkins
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - paroquia_network

volumes:
  postgres_data:
  jenkins_data:

networks:
  paroquia_network:
    driver: bridge