server {
    listen 80;
    
    # Se o usuário acessar a raiz (/), vai para o Site Público
    location / {
        proxy_pass http://frontend-site:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Se acessar /api/, o tráfego vai para o Backend Node.js
    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Você pode acessar o admin por uma porta separada ou subdomínio. 
    # Aqui, escutaremos na porta 8081 para o painel de admin.
}

server {
    listen 8081;
    location / {
        proxy_pass http://frontend-admin:80;
        proxy_set_header Host $host;
    }
}